### ISSUE TITLE
pls add responsivity

### ISSUE THREAD

**Issue by CRYPTXMNESIA** [joshterrill/hushnote#22]

**Comment by joshterrill** [comment]
Good idea. I'll add it this weekend and will let you know once it's pushed and deployed.

**Comment by CRYPTXMNESIA** [comment]
tysm also i have another idea! what about adding password to the note that you are making and send a notification to an email when the note got destroyed.

(def not privnote inspired)

**Comment by joshterrill** [comment]
I've thought about adding passwords to notes, and the reason why I haven't is because I would be worried that most people would not choose strong enough passwords to protect their messages. There is a password of sorts that already gets generated, it's the second part of the url: `https://hush.dangerous.dev/read/<message_id>/<message_key>`

In order to view a message, one needs to have both a valid message ID and message key. If you don't add a message key, you'll get an error saying it can't look the message up, and if you add a message key that doesn't match what the message ID is expecting, it will throw an error saying "Incorrect key. Note has been destroyed." If you wanted to, you could take the approach that Mega.nz does and separate the randomly generated key from the URL, deliver the URL to the person intended for the message, and then deliver the randomly generated key in a different way.

Another thing I would point out is the generated message key is NOT stored on the server or the database, so when it comes to being able to decrypt messages, not even the owner of the server that this app sits on can decrypt them, and there's something really nice about that.

In a similar vein, email notifications are a possible risk point of de-anonymization. Having a bunch of emails of people who have been creating secret messages runs the risk of someone who might be able to compromise the database or server being able to find out who sent the messages. Even if they're encrypted at rest, they still would need to be decrypted before an email is sent. This is also why the message key isn't generated, sent, or stored on the server when using the normal frontend, so if someone did compromise a server this was running on, they still wouldn't have access to the message keys that are used to decrypt the messages.

I hope all of this makes sense. I'm not totally opposed to it, though. I'll think about it as I finish up some of these other responsive changes today.

**Comment by joshterrill** [comment]
The responsive styles have been pushed and deployed.

**Comment by CRYPTXMNESIA** [comment]
niceee thank you

**Comment by CRYPTXMNESIA** [comment]
> I've thought about adding passwords to notes, and the reason why I haven't is because I would be worried that most people would not choose strong enough passwords to protect their messages. There is a password of sorts that already gets generated, it's the second part of the url: `https://hush.dangerous.dev/read/<message_id>/<message_key>`
> 
> In order to view a message, one needs to have both a valid message ID and message key. If you don't add a message key, you'll get an error saying it can't look the message up, and if you add a message key that doesn't match what the message ID is expecting, it will throw an error saying "Incorrect key. Note has been destroyed." If you wanted to, you could take the approach that Mega.nz does and separate the randomly generated key from the URL, deliver the URL to the person intended for the message, and then deliver the randomly generated key in a different way.
> 
> Another thing I would point out is the generated message key is NOT stored on the server or the database, so when it comes to being able to decrypt messages, not even the owner of the server that this app sits on can decrypt them, and there's something really nice about that.
> 
> In a similar vein, email notifications are a possible risk point of de-anonymization. Having a bunch of emails of people who have been creating secret messages runs the risk of someone who might be able to compromise the database or server being able to find out who sent the messages. Even if they're encrypted at rest, they still would need to be decrypted before an email is sent. This is also why the message key isn't generated, sent, or stored on the server when using the normal frontend, so if someone did compromise a server this was running on, they still wouldn't have access to the message keys that are used to decrypt the messages.
> 
> I hope all of this makes sense. I'm not totally opposed to it, though. I'll think about it as I finish up some of these other responsive changes today.

understandable.
